#!/bin/bash
cd test
cp ../build/libs/native-obfuscator.jar native-obfuscator.jar
mkdir current
mkdir test_build
for test_dir in `find tests -mindepth 1 -type d`
do
    test_id=`basename $test_dir`

    echo "Test #"$test_id
    # cleanup
    rm -rf current/*
    rm -rf test_build/*
    rm test_build.jar

    # compiling
    javac -d test_build $test_dir/*.java 
    rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
    jar cvfm test_build.jar DEFAULT.MF test_build/*
    rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi

    # making test
    java -jar native-obfuscator.jar test_build.jar current
    rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
    cmake current/cpp
    rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
    cmake --build current/cpp --config Release
    rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
    cp current/cpp/Release/* current/*

    # testing
    cd current
    java -jar test.jar
    rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
    cd ..
done
